import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class CrypnoteTheme {
  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff685f12),
      surfaceTint: Color(0xff685f12),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xfff1e48a),
      onPrimaryContainer: Color(0xff4f4700),
      secondary: Color(0xff4c662b),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffcdeda3),
      onSecondaryContainer: Color(0xff354e15),
      tertiary: Color(0xff406835),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffc1efaf),
      onTertiaryContainer: Color(0xff295020),
      error: Color(0xff904a43),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff73332d),
      surface: Color(0xfffff9eb),
      onSurface: Color(0xff1d1c13),
      onSurfaceVariant: Color(0xff4a473a),
      outline: Color(0xff7b7768),
      outlineVariant: Color(0xffccc6b5),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff323027),
      inversePrimary: Color(0xffd5c871),
      primaryFixed: Color(0xfff1e48a),
      onPrimaryFixed: Color(0xff201c00),
      primaryFixedDim: Color(0xffd5c871),
      onPrimaryFixedVariant: Color(0xff4f4700),
      secondaryFixed: Color(0xffcdeda3),
      onSecondaryFixed: Color(0xff102000),
      secondaryFixedDim: Color(0xffb2d189),
      onSecondaryFixedVariant: Color(0xff354e15),
      tertiaryFixed: Color(0xffc1efaf),
      onTertiaryFixed: Color(0xff012200),
      tertiaryFixedDim: Color(0xffa5d395),
      onTertiaryFixedVariant: Color(0xff295020),
      surfaceDim: Color(0xffdfdacc),
      surfaceBright: Color(0xfffff9eb),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff9f3e5),
      surfaceContainer: Color(0xfff3eee0),
      surfaceContainerHigh: Color(0xffede8da),
      surfaceContainerHighest: Color(0xffe7e2d5),
    );
  }

  ThemeData light() {
    return theme(lightScheme());
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffd5c871),
      surfaceTint: Color(0xffd5c871),
      onPrimary: Color(0xff373100),
      primaryContainer: Color(0xff4f4700),
      onPrimaryContainer: Color(0xfff1e48a),
      secondary: Color(0xffb2d189),
      onSecondary: Color(0xff1f3701),
      secondaryContainer: Color(0xff354e15),
      onSecondaryContainer: Color(0xffcdeda3),
      tertiary: Color(0xffa5d395),
      onTertiary: Color(0xff12380b),
      tertiaryContainer: Color(0xff295020),
      onTertiaryContainer: Color(0xffc1efaf),
      error: Color(0xffffb4ab),
      onError: Color(0xff561e19),
      errorContainer: Color(0xff73332d),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff15130c),
      onSurface: Color(0xffe7e2d5),
      onSurfaceVariant: Color(0xffccc6b5),
      outline: Color(0xff959181),
      outlineVariant: Color(0xff4a473a),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xffe7e2d5),
      inversePrimary: Color(0xff685f12),
      primaryFixed: Color(0xfff1e48a),
      onPrimaryFixed: Color(0xff201c00),
      primaryFixedDim: Color(0xffd5c871),
      onPrimaryFixedVariant: Color(0xff4f4700),
      secondaryFixed: Color(0xffcdeda3),
      onSecondaryFixed: Color(0xff102000),
      secondaryFixedDim: Color(0xffb2d189),
      onSecondaryFixedVariant: Color(0xff354e15),
      tertiaryFixed: Color(0xffc1efaf),
      onTertiaryFixed: Color(0xff012200),
      tertiaryFixedDim: Color(0xffa5d395),
      onTertiaryFixedVariant: Color(0xff295020),
      surfaceDim: Color(0xff15130c),
      surfaceBright: Color(0xff3b3930),
      surfaceContainerLowest: Color(0xff100e07),
      surfaceContainerLow: Color(0xff1d1c13),
      surfaceContainer: Color(0xff212017),
      surfaceContainerHigh: Color(0xff2c2a21),
      surfaceContainerHighest: Color(0xff37352c),
    );
  }

  ThemeData dark() {
    return theme(darkScheme());
  }

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
    useMaterial3: true,
    brightness: colorScheme.brightness,
    colorScheme: colorScheme,
    textTheme: TextTheme(
      displayLarge: GoogleFonts.getTextTheme('Roboto').displayLarge,
      displayMedium: GoogleFonts.getTextTheme('Roboto').displayMedium,
      displaySmall: GoogleFonts.getTextTheme('Roboto').displaySmall,
      headlineLarge: GoogleFonts.getTextTheme('Roboto').headlineLarge,
      headlineMedium: GoogleFonts.getTextTheme('Roboto').headlineMedium,
      headlineSmall: GoogleFonts.getTextTheme('Roboto').headlineSmall,
      bodyLarge: GoogleFonts.getTextTheme('Open Sans').bodyLarge,
      bodyMedium: GoogleFonts.getTextTheme('Open Sans').bodyMedium,
      bodySmall: GoogleFonts.getTextTheme('Open Sans').bodySmall,
      titleLarge: GoogleFonts.getTextTheme('Open Sans').titleLarge,
      titleMedium: GoogleFonts.getTextTheme('Open Sans').titleMedium,
      titleSmall: GoogleFonts.getTextTheme('Open Sans').titleSmall,
      labelLarge: GoogleFonts.getTextTheme('Open Sans').labelLarge,
      labelMedium: GoogleFonts.getTextTheme('Open Sans').labelMedium,
      labelSmall: GoogleFonts.getTextTheme('Open Sans').labelSmall,
    ),
    scaffoldBackgroundColor: colorScheme.surface,
    canvasColor: colorScheme.surfaceContainer,
  );
}
