// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'lang.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Lang _$LangFromJson(Map<String, dynamic> json) => _Lang(
  id: json['id'] as String,
  numberargument: json['numberargument'] as String,
  stringargument: json['stringargument'] as String,
  welcome: json['welcome'] as String,
  spontanious: json['spontanious'] as String,
  signin: json['signin'] as String,
  username: json['username'] as String,
  password: json['password'] as String,
  loginbutton: json['loginbutton'] as String,
  createaccount: json['createaccount'] as String,
  policy: json['policy'] as String,
  applicationName: json['applicationName'] as String,
  applicationVersion: json['applicationVersion'] as String,
  applicationLegalese: json['applicationLegalese'] as String,
  errorPasswordValidation: json['errorPasswordValidation'] as String,
  authenticationsuccessful: json['authenticationsuccessful'] as String,
  authenticationExceptionMessage:
      json['authenticationExceptionMessage'] as String,
  register: json['register'] as String,
  registerheadline: json['registerheadline'] as String,
  registertitle: json['registertitle'] as String,
  registerbutton: json['registerbutton'] as String,
  emptyUsernameValidation: json['emptyUsernameValidation'] as String,
  charUsernameValidation: json['charUsernameValidation'] as String,
  emptyPasswordValidation: json['emptyPasswordValidation'] as String,
  charPasswordValidation: json['charPasswordValidation'] as String,
  registerNow: json['registerNow'] as String,
  registersuccessful: json['registersuccessful'] as String,
  registerfailed: json['registerfailed'] as String,
  setuppindecryption: json['setuppindecryption'] as String,
  createpinbutton: json['createpinbutton'] as String,
  pincreatesuccessful: json['pincreatesuccessful'] as String,
  pincreatedfailed: json['pincreatedfailed'] as String,
  greetingday: json['greetingday'] as String,
  clock: json['clock'] as String,
  userloggedin: json['userloggedin'] as String,
  dashboard: json['dashboard'] as String,
  totalDashboardTitle: json['totalDashboardTitle'] as String,
  totalDashboardLabel: json['totalDashboardLabel'] as String,
  waitingDashboardTitle: json['waitingDashboardTitle'] as String,
  waitingDashboardLabel: json['waitingDashboardLabel'] as String,
  deletedDashboardTitle: json['deletedDashboardTitle'] as String,
  deletedDashboardLabel: json['deletedDashboardLabel'] as String,
  importanceDashboardTitle: json['importanceDashboardTitle'] as String,
  importanceDashboardLabel: json['importanceDashboardLabel'] as String,
  createpininformation: json['createpininformation'] as String,
  erroremptypinvalidation: json['erroremptypinvalidation'] as String,
  errorcharspinvalidation: json['errorcharspinvalidation'] as String,
  encryption: json['encryption'] as String,
  createcrypnote: json['createcrypnote'] as String,
  decryptionschedulenonactive: json['decryptionschedulenonactive'] as String,
  decryptionscheduleactive: json['decryptionscheduleactive'] as String,
  importancelevel: json['importancelevel'] as String,
  encrytionbutton: json['encrytionbutton'] as String,
  encryptionsuccessful: json['encryptionsuccessful'] as String,
  encryptionfailed: json['encryptionfailed'] as String,
  encryptioncollectionitemdeleteconfirmationtitle:
      json['encryptioncollectionitemdeleteconfirmationtitle'] as String,
  encryptioncollectionitemdeletionaccepted:
      json['encryptioncollectionitemdeletionaccepted'] as String,
  encryptioncollectionitemdeletiondeclined:
      json['encryptioncollectionitemdeletiondeclined'] as String,
  emptycollection: json['emptycollection'] as String,
  encryptioncollectionitemlatestdecryptiontitle:
      json['encryptioncollectionitemlatestdecryptiontitle'] as String,
  encryptioncollectionitemlatestdecryptiondatestamp:
      json['encryptioncollectionitemlatestdecryptiondatestamp'] as String,
  recycleitemdeletedtitle: json['recycleitemdeletedtitle'] as String,
  recycledeleteddatestamp: json['recycledeleteddatestamp'] as String,
  recycledestroytooltip: json['recycledestroytooltip'] as String,
  recyclerestoretooltip: json['recyclerestoretooltip'] as String,
  emptyrecycle: json['emptyrecycle'] as String,
  profile: json['profile'] as String,
  yours: json['yours'] as String,
  usernameprofile: json['usernameprofile'] as String,
  firstnameprofile: json['firstnameprofile'] as String,
  lastnameprofile: json['lastnameprofile'] as String,
  preferences: json['preferences'] as String,
  algorithmpreferenceslabel: json['algorithmpreferenceslabel'] as String,
  algoritmpreferences: json['algoritmpreferences'] as String,
  secretkeypreferenceslabel: json['secretkeypreferenceslabel'] as String,
  secretkeypreferences: json['secretkeypreferences'] as String,
  thememodepreferenceslabel: json['thememodepreferenceslabel'] as String,
  thememodepreferences: json['thememodepreferences'] as String,
  modifyprofilepopmenu: json['modifyprofilepopmenu'] as String,
  changeencryptorpopmenu: json['changeencryptorpopmenu'] as String,
  aboutpopmenu: json['aboutpopmenu'] as String,
  logoutpopmenu: json['logoutpopmenu'] as String,
  modifyprofiletitle: json['modifyprofiletitle'] as String,
  newusername: json['newusername'] as String,
  newfirstname: json['newfirstname'] as String,
  newlastname: json['newlastname'] as String,
  modifyusernameinformation: json['modifyusernameinformation'] as String,
  modifyencryptortitle: json['modifyencryptortitle'] as String,
  modifyencryptoralgorithmselected:
      json['modifyencryptoralgorithmselected'] as String,
  modifyencryptoralgorithmdescriptionselected:
      json['modifyencryptoralgorithmdescriptionselected'] as String,
  modifysecreykeyinformation: json['modifysecreykeyinformation'] as String,
  logoutconfirmation: json['logoutconfirmation'] as String,
  logoutconfirmationaccepted: json['logoutconfirmationaccepted'] as String,
  logoutconfirmationdeclined: json['logoutconfirmationdeclined'] as String,
  nearestdecryption: json['nearestdecryption'] as String,
  nearestdecryptionhoursremaining:
      json['nearestdecryptionhoursremaining'] as String,
  nearesthourscountdown: json['nearesthourscountdown'] as String,
  nearestdecryptionsheduleat: json['nearestdecryptionsheduleat'] as String,
  latestdecyption: json['latestdecyption'] as String,
  latestdecryptiondatestamp: json['latestdecryptiondatestamp'] as String,
  latestdecryptionhours: json['latestdecryptionhours'] as String,
  latestdecryptioncodecrypt: json['latestdecryptioncodecrypt'] as String,
);

Map<String, dynamic> _$LangToJson(_Lang instance) => <String, dynamic>{
  'id': instance.id,
  'numberargument': instance.numberargument,
  'stringargument': instance.stringargument,
  'welcome': instance.welcome,
  'spontanious': instance.spontanious,
  'signin': instance.signin,
  'username': instance.username,
  'password': instance.password,
  'loginbutton': instance.loginbutton,
  'createaccount': instance.createaccount,
  'policy': instance.policy,
  'applicationName': instance.applicationName,
  'applicationVersion': instance.applicationVersion,
  'applicationLegalese': instance.applicationLegalese,
  'errorPasswordValidation': instance.errorPasswordValidation,
  'authenticationsuccessful': instance.authenticationsuccessful,
  'authenticationExceptionMessage': instance.authenticationExceptionMessage,
  'register': instance.register,
  'registerheadline': instance.registerheadline,
  'registertitle': instance.registertitle,
  'registerbutton': instance.registerbutton,
  'emptyUsernameValidation': instance.emptyUsernameValidation,
  'charUsernameValidation': instance.charUsernameValidation,
  'emptyPasswordValidation': instance.emptyPasswordValidation,
  'charPasswordValidation': instance.charPasswordValidation,
  'registerNow': instance.registerNow,
  'registersuccessful': instance.registersuccessful,
  'registerfailed': instance.registerfailed,
  'setuppindecryption': instance.setuppindecryption,
  'createpinbutton': instance.createpinbutton,
  'pincreatesuccessful': instance.pincreatesuccessful,
  'pincreatedfailed': instance.pincreatedfailed,
  'greetingday': instance.greetingday,
  'clock': instance.clock,
  'userloggedin': instance.userloggedin,
  'dashboard': instance.dashboard,
  'totalDashboardTitle': instance.totalDashboardTitle,
  'totalDashboardLabel': instance.totalDashboardLabel,
  'waitingDashboardTitle': instance.waitingDashboardTitle,
  'waitingDashboardLabel': instance.waitingDashboardLabel,
  'deletedDashboardTitle': instance.deletedDashboardTitle,
  'deletedDashboardLabel': instance.deletedDashboardLabel,
  'importanceDashboardTitle': instance.importanceDashboardTitle,
  'importanceDashboardLabel': instance.importanceDashboardLabel,
  'createpininformation': instance.createpininformation,
  'erroremptypinvalidation': instance.erroremptypinvalidation,
  'errorcharspinvalidation': instance.errorcharspinvalidation,
  'encryption': instance.encryption,
  'createcrypnote': instance.createcrypnote,
  'decryptionschedulenonactive': instance.decryptionschedulenonactive,
  'decryptionscheduleactive': instance.decryptionscheduleactive,
  'importancelevel': instance.importancelevel,
  'encrytionbutton': instance.encrytionbutton,
  'encryptionsuccessful': instance.encryptionsuccessful,
  'encryptionfailed': instance.encryptionfailed,
  'encryptioncollectionitemdeleteconfirmationtitle':
      instance.encryptioncollectionitemdeleteconfirmationtitle,
  'encryptioncollectionitemdeletionaccepted':
      instance.encryptioncollectionitemdeletionaccepted,
  'encryptioncollectionitemdeletiondeclined':
      instance.encryptioncollectionitemdeletiondeclined,
  'emptycollection': instance.emptycollection,
  'encryptioncollectionitemlatestdecryptiontitle':
      instance.encryptioncollectionitemlatestdecryptiontitle,
  'encryptioncollectionitemlatestdecryptiondatestamp':
      instance.encryptioncollectionitemlatestdecryptiondatestamp,
  'recycleitemdeletedtitle': instance.recycleitemdeletedtitle,
  'recycledeleteddatestamp': instance.recycledeleteddatestamp,
  'recycledestroytooltip': instance.recycledestroytooltip,
  'recyclerestoretooltip': instance.recyclerestoretooltip,
  'emptyrecycle': instance.emptyrecycle,
  'profile': instance.profile,
  'yours': instance.yours,
  'usernameprofile': instance.usernameprofile,
  'firstnameprofile': instance.firstnameprofile,
  'lastnameprofile': instance.lastnameprofile,
  'preferences': instance.preferences,
  'algorithmpreferenceslabel': instance.algorithmpreferenceslabel,
  'algoritmpreferences': instance.algoritmpreferences,
  'secretkeypreferenceslabel': instance.secretkeypreferenceslabel,
  'secretkeypreferences': instance.secretkeypreferences,
  'thememodepreferenceslabel': instance.thememodepreferenceslabel,
  'thememodepreferences': instance.thememodepreferences,
  'modifyprofilepopmenu': instance.modifyprofilepopmenu,
  'changeencryptorpopmenu': instance.changeencryptorpopmenu,
  'aboutpopmenu': instance.aboutpopmenu,
  'logoutpopmenu': instance.logoutpopmenu,
  'modifyprofiletitle': instance.modifyprofiletitle,
  'newusername': instance.newusername,
  'newfirstname': instance.newfirstname,
  'newlastname': instance.newlastname,
  'modifyusernameinformation': instance.modifyusernameinformation,
  'modifyencryptortitle': instance.modifyencryptortitle,
  'modifyencryptoralgorithmselected': instance.modifyencryptoralgorithmselected,
  'modifyencryptoralgorithmdescriptionselected':
      instance.modifyencryptoralgorithmdescriptionselected,
  'modifysecreykeyinformation': instance.modifysecreykeyinformation,
  'logoutconfirmation': instance.logoutconfirmation,
  'logoutconfirmationaccepted': instance.logoutconfirmationaccepted,
  'logoutconfirmationdeclined': instance.logoutconfirmationdeclined,
  'nearestdecryption': instance.nearestdecryption,
  'nearestdecryptionhoursremaining': instance.nearestdecryptionhoursremaining,
  'nearesthourscountdown': instance.nearesthourscountdown,
  'nearestdecryptionsheduleat': instance.nearestdecryptionsheduleat,
  'latestdecyption': instance.latestdecyption,
  'latestdecryptiondatestamp': instance.latestdecryptiondatestamp,
  'latestdecryptionhours': instance.latestdecryptionhours,
  'latestdecryptioncodecrypt': instance.latestdecryptioncodecrypt,
};
